version = 1

exclude_patterns = [
  "venv/**"
]

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "python"
dependency_file_paths = ["pyproject.toml"]
enabled = true

[[transformers]]
name = "ruff"
enabled = true

[[transformers]]
name = "isort"
enabled = true
