version = 1

exclude_patterns = [
  "venv/**",
  "**/migrations/**",
]

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "python"
dependency_file_paths = ["requirements.txt"]
enabled = true

[[transformers]]
name = "ruff"
enabled = true

[[transformers]]
name = "isort"
enabled = true
